#!/usr/bin/env python3
"""
STEPP Inference Node — ROS 2 Humble port.

Subscribes to /camera/color/image_raw/compressed (CompressedImage),
runs DINOv2 + SLIC + MLP traversability inference,
publishes traversability cost as Float32Stamped and overlay Image.
"""

import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, QoSReliabilityPolicy, QoSDurabilityPolicy, QoSHistoryPolicy

from sensor_msgs.msg import Image, CompressedImage
from std_msgs.msg import Float32MultiArray, MultiArrayDimension
import torch
import cv2
from cv_bridge import CvBridge
import numpy as np
import torch.nn as nn
from PIL import Image as PILImage
from torchvision import transforms
from matplotlib import cm
import warnings
from queue import Queue
from threading import Thread, Lock

# Custom message (generated by rosidl at build time)
from stepp_ros2_humble.msg import Float32Stamped

from STEPP.DINO.backbone import get_backbone
from STEPP.DINO.dino_feature_extract import DinoInterface
from STEPP.DINO.dino_feature_extract import get_dino_features, average_dino_feature_segment, average_dino_feature_segment_tensor
from STEPP.SLIC.slic_segmentation import SLIC
from STEPP.model.mlp import ReconstructMLP

warnings.filterwarnings("ignore")
CV_BRIDGE = CvBridge()
TO_TENSOR = transforms.ToTensor()
TO_PIL_IMAGE = transforms.ToPILImage()

from pytictac import Timer


class InferenceNode(Node):
    def __init__(self):
        super().__init__('inference_node')

        # ------------------------------------------------------------
        # QoS profiles
        # ------------------------------------------------------------
        # Camera images typically use BEST_EFFORT reliability
        sensor_qos = QoSProfile(
            reliability=QoSReliabilityPolicy.BEST_EFFORT,
            history=QoSHistoryPolicy.KEEP_LAST,
            depth=1
        )
        # Reliable QoS for inference output
        reliable_qos = QoSProfile(
            reliability=QoSReliabilityPolicy.RELIABLE,
            history=QoSHistoryPolicy.KEEP_LAST,
            depth=10
        )

        # ------------------------------------------------------------
        # Parameters
        # ------------------------------------------------------------
        self.declare_parameter('model_path', '')
        self.declare_parameter('ump', True)
        self.declare_parameter('cutoff', 1.2)
        self.declare_parameter('visualize', False)

        model_path = self.get_parameter('model_path').get_parameter_value().string_value
        self.ump = self.get_parameter('ump').get_parameter_value().bool_value
        self.cutoff = self.get_parameter('cutoff').get_parameter_value().double_value
        self.visualize = self.get_parameter('visualize').get_parameter_value().bool_value

        self.get_logger().info(f'cutoff = {self.cutoff}')
        self.get_logger().info(f'ump    = {self.ump}')

        # ------------------------------------------------------------
        # Thread-safe image queue
        # ------------------------------------------------------------
        self.image_queue = Queue(maxsize=1)
        self.lock = Lock()
        self.processing = False

        # ------------------------------------------------------------
        # Subscribers & publishers
        # ------------------------------------------------------------
        self.image_sub = self.create_subscription(
            CompressedImage,
            '/camera/color/image_raw/compressed',
            self.image_callback,
            sensor_qos
        )

        self.inference_pub = self.create_publisher(
            Float32MultiArray,
            '/inference/result',
            reliable_qos
        )
        self.inference_stamped_pub = self.create_publisher(
            Float32Stamped,
            '/inference/results_stamped_post',
            reliable_qos
        )
        self.visu_traversability_pub = self.create_publisher(
            Image,
            '/inference/visu_traversability_post',
            reliable_qos
        )

        # ------------------------------------------------------------
        # Device & threshold
        # ------------------------------------------------------------
        self.threshold = 0.2
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Settings
        self.size = 700
        self.dino_size = "vit_small"
        self.patch = 14
        self.backbone_type = "dinov2"

        # ------------------------------------------------------------
        # DINOv2 feature extractor
        # ------------------------------------------------------------
        self.di = DinoInterface(
            device=self.device,
            backbone=self.backbone_type,
            input_size=self.size,
            backbone_type=self.dino_size,
            patch_size=self.patch,
            interpolate=False,
            use_mixed_precision=self.ump,
        )

        self.slic = SLIC(crop_x=0, crop_y=0)

        # ------------------------------------------------------------
        # MLP reconstruction model
        # ------------------------------------------------------------
        self.model = ReconstructMLP(384, [256, 128, 64, 32, 64, 128, 256])

        if not model_path:
            self.get_logger().fatal("Parameter 'model_path' is required (path to .pth checkpoint).")
            raise RuntimeError("model_path parameter not set")

        state_dict = torch.load(model_path, map_location=self.device)
        self.model.load_state_dict(state_dict)
        self.model.to(self.device)
        self.model.eval()

        # ------------------------------------------------------------
        # Start processing thread
        # ------------------------------------------------------------
        self.thread = Thread(target=self.process_images, daemon=True)
        self.thread.start()

        self.get_logger().info('Inference node initialized')

    # ------------------------------------------------------------------
    # Publishers
    # ------------------------------------------------------------------
    def publish_matrix(self, matrix):
        msg = Float32MultiArray()
        msg.data = matrix.flatten().tolist()
        msg.layout.dim.append(MultiArrayDimension())
        msg.layout.dim[0].label = "rows"
        msg.layout.dim[0].size = matrix.shape[0]
        msg.layout.dim[0].stride = matrix.shape[1]
        msg.layout.dim.append(MultiArrayDimension())
        msg.layout.dim[1].label = "columns"
        msg.layout.dim[1].size = matrix.shape[1]
        msg.layout.dim[1].stride = 1
        self.inference_pub.publish(msg)

    def publish_array_stamped(self, matrix):
        msg = Float32Stamped()
        # ROS 2 timestamp: get_clock().now() returns a Time object, .to_msg() gives builtin_interfaces.msg.Time
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.header.frame_id = 'camera'

        msg.data = Float32MultiArray()
        msg.data.data = matrix.flatten().tolist()
        msg.data.layout.dim.append(MultiArrayDimension())
        msg.data.layout.dim[0].label = "rows"
        msg.data.layout.dim[0].size = matrix.shape[0]
        msg.data.layout.dim[0].stride = matrix.shape[1]
        msg.data.layout.dim.append(MultiArrayDimension())
        msg.data.layout.dim[1].label = "columns"
        msg.data.layout.dim[1].size = matrix.shape[1]
        msg.data.layout.dim[1].stride = 1
        self.inference_stamped_pub.publish(msg)

    # ------------------------------------------------------------------
    # Processing thread
    # ------------------------------------------------------------------
    def process_images(self):
        while rclpy.ok():
            image_data = self.image_queue.get()
            if image_data is None:
                break

            with self.lock:
                if isinstance(image_data, CompressedImage):
                    cv_image = CV_BRIDGE.compressed_imgmsg_to_cv2(image_data, desired_encoding="bgr8")
                else:
                    cv_image = CV_BRIDGE.imgmsg_to_cv2(image_data, desired_encoding="bgr8")

                try:
                    traversability_array, inference_img = self.inference_image(cv_image)
                except Exception as e:
                    self.get_logger().error(f'Inference error: {e}')
                    self.processing = False
                    continue

                self.publish_array_stamped(traversability_array)

                if self.visualize and inference_img is not None:
                    self.visu_traversability_pub.publish(
                        CV_BRIDGE.cv2_to_imgmsg(np.array(inference_img), "rgb8")
                    )

            self.processing = False

    # ------------------------------------------------------------------
    # Core inference (unchanged from ROS 1 version)
    # ------------------------------------------------------------------
    def inference_image(self, image):
        # Load an image
        org_img = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        img = cv2.resize(org_img, (self.size, self.size))
        H, W, D = org_img.shape

        # DINO feature extraction
        torch_img = torch.from_numpy(img)
        torch_img = torch_img.permute(2, 0, 1)
        torch_img = (torch_img.type(torch.float32) / 255)[None].to(self.device)
        dino_size = 'vit_small'
        features = self.di.inference(torch_img)

        # SLIC segmentation
        segments, segmented_image = self.slic.Slic_segmentation_for_all_pixels_torch(img)

        # Resize segment map to DINO feature resolution
        resized_segmented_img, new_segment_dict = self.slic.make_masks_smaller_torch(
            segments, segmented_image, int(self.size / self.patch), return_dict=False
        )

        # Average features over segments
        average_features = average_dino_feature_segment_tensor(
            features, resized_segmented_img
        ).to(self.device)

        # MLP forward pass
        reconstructed_features = self.model(average_features)

        # Reconstruction loss
        loss_fn = nn.MSELoss(reduction='none')
        losses = loss_fn(average_features, reconstructed_features)
        losses = losses.mean(dim=1).cpu().detach().numpy()

        # Map losses back to pixel space
        segmented_image = segmented_image.cpu().detach().numpy()
        unique_keys = np.unique(resized_segmented_img.cpu().detach().numpy()).astype(int)
        max_segment_value = np.max(segmented_image)
        default_loss = 1.0
        mapping_array = np.full(max_segment_value + 1, default_loss)
        mapping_array[unique_keys] = losses
        segmented_image = mapping_array[segmented_image]

        # Clamp and normalize
        segmented_image = np.where(segmented_image > 10, 10, segmented_image)
        segmented_image = (
            (segmented_image - segmented_image.min())
            / (segmented_image.max() - segmented_image.min())
        ) * self.cutoff

        segmented_image = np.where(
            segmented_image > self.threshold, self.threshold, segmented_image
        )

        if self.visualize:
            # Colormap
            s = 0.3
            cmap = cm.get_cmap("RdYlBu", 256)
            cmap = np.vstack([
                cmap(np.linspace(0, s, 128)),
                cmap(np.linspace(1 - s, 1.0, 128)),
            ])
            cmap = (cmap[:, :3] * 255).astype(np.uint8)
            cmap = cmap[::-1]

            # Normalize to [0, 255]
            segmented_normalized = (
                (segmented_image - segmented_image.min())
                / (segmented_image.max() - segmented_image.min() + 1e-8)
                * 255
            ).astype(np.uint8)

            # Map to colors
            color_mapped_img = cmap[segmented_normalized]

            # Alpha composite
            img_rgba = PILImage.fromarray(np.uint8(img)).convert("RGBA")
            seg_rgba = PILImage.fromarray(color_mapped_img).convert("RGBA")
            seg_rgba_np = np.array(seg_rgba)
            alpha_channel = seg_rgba_np[:, :, 3]
            alpha_channel = (alpha_channel * 0.5).astype(np.uint8)
            seg_rgba_np[:, :, 3] = alpha_channel
            seg_rgba = PILImage.fromarray(seg_rgba_np)

            img_new = PILImage.alpha_composite(img_rgba, seg_rgba)
            img_rgb = img_new.convert("RGB")

            # Resize back to original
            img_rgb = img_rgb.resize((W, H))
            segmented_image = cv2.resize(segmented_image, (W, H))

            return segmented_image, img_rgb
        else:
            segmented_image = cv2.resize(segmented_image, (W, H))
            return segmented_image, None

    # ------------------------------------------------------------------
    # Subscriber callback
    # ------------------------------------------------------------------
    def image_callback(self, data):
        if not self.processing:
            with self.lock:
                if not self.image_queue.full():
                    self.image_queue.put(data)
                    self.processing = True


def main():
    rclpy.init()
    node = InferenceNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == '__main__':
    main()
